### ISSUE TITLE
lua binding of liblaxjson

### ISSUE THREAD

**Issue by sjnam** [andrewrk/liblaxjson#1]
Thank you for providing this awesome json parser.

minor bug:
You should `lax_json_destroy(context)` before return errors in the following lines.
- https://github.com/andrewrk/liblaxjson/blob/master/example/token_list.c#L74
- https://github.com/andrewrk/liblaxjson/blob/master/example/token_list.c#L80

I wrote [lua binding](https://github.com/sjnam/lua-laxjson) of liblaxjson.

**Comment by andrewrk** [comment]
Oops, forgot to reply to this. Cool! And thanks for the bug report :+1:

**Comment by andrewrk** [comment]
I added your project to the README.
